purpleidea/mgmt

README.md
Your advice in #5 worked nicely. Debian apparently does not (yet) package `stringer`, so let's mention it and give help.
=> README: also list stringer as a dependency

test.sh
The test.sh script aborts as soon as a test fails. This can save time
on the local machine, but is inconvenient in CI where an early minor
failure can mask more severe errors that will be found later.
=> don't abort test suite on first failure

DOCUMENTATION.md, README.md
This consolidates how-to at the right place for the docs.
=> move systemd tip from README to DOCUMENTATION

exec.go, file.go, noop.go, pgraph.go, pkg.go, svc.go
The naming was confusing because the boolean return value expresses
whether the resource needed changing (the check failed) as opposed to
the state not being not OK.
purpleidea note: The "stateok" (now properly renamed to "checkok") is
actually the historical bool return value of the Check() -> bool
function which is now part of the CheckApply() amalgamation. This is an
easy way to think about it if you're trying to understand why at the end
of a successful apply we return false, nil.
=> rename the 'stateok' return value to 'checkok'

pkg.go
We forgot to cache the state when we are converged. This avoids
repetitive checking when we hit repeated backpoke()'s for example.
=> Pkg: cache state when it is correct

README.md, main.go, puppet.go
Puppet can be used on the basis of the `ffrank-mgmtgraph` module.
There are three modes available:
* fetching catalogs from the master (--puppet agent)
* compiling a manifest from a local file (--puppet /path/to/file.pp)
* compiling a manifest from the cli (--puppet "<manifest>")
Catalogs from the master are currently never refreshed. We should
add some more code to re-run the parsing function at an interval
equal to Puppet's local 'runinterval' setting.
There is also still a distinct lack of tests.
Still, this fixes #8
=> Puppet integration

README.md
Just watched the recording from DebConf, checked out the repo and saw that the video link was  missing.
Fixed  :+1:
=> Add recording and slides from DebConf16 presentation by James Shubin

Makefile
According to the documentation for uname:
-m, --machine
print the machine hardware name
-i, --hardware-platform
print the hardware platform (non-portable)
So use the portable -m version.
=> Change "uname -i" to "uname -m" to be portable

Makefile
If the $(shell ...) command fails, the ':=' operator fails as well
preventing variable overrides from functioning.
Wrap the assignment in an $(or ...) to prevent the shell script from
running if the variable is set from the command line or the environment.
Fixes issue #58
=> Allow make overrides of version if git fails

misc/make-deps.sh
```
../../akrennmair/gopcap/pcap.go:12:18: fatal error: pcap.h: No such file or directory
compilation terminated.
vendor/github.com/coreos/etcd/cmd/vendor/github.com/akrennmair/gopcap/pcap.go:12:18: fatal error: pcap.h: No such file or directory
compilation terminated.
```
`make deps` returns this error on Ubuntu 16.04. The added dependency solve this issue.
=> Add pcap.h dependency on Debian/Ubuntu

README.md
Add the link to the dependencise github.com/rgbkrk/libvirt-go
=> Add the link to a new dependencies in README.md

README.md
"go get" requires a package name
=> readme: Fix go get command

misc/make-deps.sh
Just a small fix to prefer DNF when present.
This will avoid warnings issues by the wrapper script.
=> misc: Prefer dnf over yum when present

Makefile, spec.in
Minor fixes for ``rpmlint`` errors:
- Switched spces to tabs
- Added quiet switch to setup
=> spec: Fix rpmlint warnings

.gitmodules, docs/documentation.md, examples/augeas1.yaml, misc/make-deps.sh, resources/augeas.go, test/shell/augeas-1.sh, test/shell/augeas-1.yaml, yamlgraph/gconfig.go
I open this pull request to get continuous feedback during all my work.
=> Augeas resource

resources/file.go
=> resources: file: do not run chownCheckApply in noop mode

docs/prometheus.md, prometheus/prometheus.go, test/shell/prometheus-1.sh
That metric is useless as by default the prometheus golang client
provides the `process_start_time_seconds` metric.
This reverts commit 25e2af7c89a7b91ffc21e29271ebf4970d59811c.
=> prometheus: Remove mgmt_process_start_time_seconds metric

Makefile
It is really strange that whe I run make, it does not build mgmt. This
commit makes build the default target, without moving the target,
therefore we keep as much as we can the order of the file.
This also removes the confusion for designers that would run "make"
instead of "make art", whose work would be disrupted when we add a --
let's say -- make alpharelese command.
=> compilation: Make build the default target

pgraph/actions.go, prometheus/prometheus.go
That pattern will be reused in future metrics.
=> prometheus: Move the prometheus nil check inside the prometheus function

.travis.yml
This should fix an issue with turning on travis for any mgmt fork.
=> travis: Add go_import_path

lib/cli.go, resources/augeas.go, resources/exec.go, resources/file.go, resources/hostname.go, resources/kv.go, resources/msg.go, resources/noop.go, resources/nspawn.go, resources/password.go, resources/pkg.go, resources/resources.go, resources/svc.go, resources/timer.go, resources/virt.go, yamlgraph2/gapi.go, yamlgraph2/gconfig.go
Subset of #143 with just refactoring of YAML parser
Avoid use of the reflect package, and use an extensible list of registred
resource kinds. This also has the benefit of removing the empty VirtRes and
AugeasRes struct types when compiling without libvirt and libaugeas.
=> yamlgraph: refactor parsing

Vagrantfile
Without packagekit the 'pkg' resources can not be used
=> vagrant: Setup Packagekit in the box

examples/graph0.hcl, examples/graph1.hcl, hcl/gapi.go, hcl/parse.go, lib/cli.go
This adds a really basic hcl frontend for mgmt. please check out the example for usage.
I was pondering the idea of embedding edge definition into the resource like the following:
```hcl
resource "noop" "donothing" {}
resource "file" "myfile" {
...
depends_on = ["noop.donothing"]
}
```
I have not added this as I wanted to get your opinion on the idea.
=> WIP: HCL Frontend

examples/graph0.hcl, hcl/parse.go
This removes the `edge` type in hcl and adds a `depends_on` field in the `resource` type
For example.
```
edge "e1" {
from = {
kind = "noop"
name = "noop1"
}
to = {
kind = "file"
name = "file1"
}
}
```
can now be done in the `resource` that is going to be the "to" node of the edge. It uses the syntax of `<resource-type>.<resource-name>`
```
resource "file" "file1" {
path = "/tmp/mgmt-hello-world"
content = "hello, world"
state = "exists"
depends_on = ["noop.noop1"]
}
```
=> hcl: Removed edge object in favor of depends_on field in resource

examples/hil.hcl, hcl/parse.go, hil/interpolate.go, resources/resources.go, resources/sendrecv.go
This adds string interpolation to fields in hcl frontend, allowing for declarative `Receiver` support and automatically creates edges for resources that use values from other resources.
*Example*
```
resource "file" "file1" {
path = "/tmp/mgmt-hello-world"
content = "${exec.sleep.Output}"
state = "exists"
}
resource "exec" "sleep" {
cmd = "echo hello"
}
```
The following will create a file at `/tmp/mgmt-hello-world` with `hello` as the contents.
*Gotchas:*
- currently you need to capitalize the field name (i.e. `Output`)
=> hcl: added hil string interpolation to hcl frontend

Vagrantfile
Solution: increase amount of RAM allocated to boxes backed by libvirt
=> Problem: go compiler fails when using libvirt provider for vagrant

vagrant/mgmt.bashrc
gometalinter failed because it's not in $PATH
=> vagrant: Fix PATH.

resources/packagekit/packagekit.go
Fixes #80 
Packagekit has its own cache and if that cache is empty or invalid it won't refresh it automatically
=> resources: Refresh packagekit cache before install

resources/aws_ec2.go
Moved the waitgroup and channels into the resource struct to prepare for additional watch methods.
=> Refactor channels and waitgroup

docker/Dockerfile, docker/Dockerfile.development
The containers were still using docker 1.6.
Also added a chown as I couldn't make build inside the development container due to permission issues.
=> docker: Bump to golang 1.8

.travis.yml
Finally works. Turns out travis sets remote.origin.fetch to a temporary version of the master branch, so we have to override with our own remote.origin.fetch before we fetch.
=> travis: Allow travis builds to access target branches

lib/main.go, prometheus/prometheus.go, resources/resources.go, resources/resources_test.go
It is recommended by Prometheus to initialize metrics:
https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics
This commits initialize the mgmt_checkapply_total metric
for each registered resource.
```topic: Capitalized message with no trailing period```
or:
```topic, topic2: Capitalized message with no trailing period```
```
```
```
```
```
git push …
```
=> prometheus: Initialize mgmt_checkapply_total metrics

puppet/puppet.go
This solves an issue first observed with golang 1.8.
Creating an exec.Command with an empty string parameter (when no puppet.conf
file is specified) would lead to an error from Puppet, stating that an
unexpected argument was passed to "puppet mgmtgraph print".
The workaround is to not include *any* positional argument (not even the
empty string) when --puppet-conf is not used.
=> puppet: avoid empty parameters to puppet mgmtgraph

resources/aws_ec2.go
=> resources: aws: ec2: Fix closed channel error in snsWatch and longpollWatch

pgraph/graphviz.go
title says it all. Solves: 
```
Error: out.dot@faalserver: syntax error in line 1 near '.'
```
=> misc: fix graphviz output for hostnames with dot in them.

.travis.yml
Only build 1 OSX environment as these are sparse so these build potentially spend a long time in the queue.
Retry the initial apt update as travis is often having troubles with it.
=> Improve CI build time and reduce needless failures

Makefile
This makes the output more readable in my terminal.
=> build: Relocate time command to the front for readability

resources/svc.go
There seems to be a "activating" state that some services can reach.
Related #369
=> resources: svc: Add activating state

engine/resources/packagekit/packagekit.go
Arch Linux uses the mapping architecture name 'any'. This mapping was
missing from mgmt resulting in an error stating that arch 'any' did not
exist. Adding this mapping allows successful installation of packages
under Arch Linux.
=> Add Arch mapping 'any' for Arch Linux compatibility

engine/resources/file_test.go, engine/resources/test_test.go, test/test-govet.sh
One of our contributors occasionally made this typo, and since core go
vet didn't (surprisingly) catch it, we should add a test!
/cc @jonathangold (present for you!)
=> test: Catch scenarios where we forgot to prefix the error with return

Vagrantfile, vagrant/motd
While checking out your interesting work, I noticed a few things:
- the go 1.8 release in fedora 26 seems to be too old to build mgmt, so I bumped the base image to fedora 28 which seems to work fine.
- the gem package manager seems to be needed during the build process but wasn't installed.
- the path to the example yaml file in motd changed, presumably when mgmt lang has been introduced.
=> Update vagrant vm

engine/resources/packagekit/packagekit.go
I broke packagekit with commit 299080f5 due to a missing equals sign
in the DBus AddMatch rule. This commit adds the necessary equals sign.
Fixes #410 and #397 
Sorry, my bad. :P
=> engine: resources: packagekit: Fix dbus addmatch rule

.travis.yml, docs/quick-start-guide.md, examples/lib/exec-send-recv.go, examples/lib/libmgmt-subgraph0.go, examples/lib/libmgmt-subgraph1.go, examples/lib/libmgmt2.go, examples/lib/libmgmt3.go, lang/funcs/core/template_polyfunc.go, lang/structs.go, test/test-gofmt.sh, test/test-govet.sh
This requires breaking changes in gofmt. This also moves to the latest stable etcd.
I'm planning to rebase and push this patch around July 31st when golang 1.11 comes out. Earlier if we need it for something specific. I'm hacking with 1.10 now.
=> travis: Bump to golang 1.10

engine/resources/cron.go, engine/resources/svc.go, examples/lang/cron4.mcl
For early feedback. Still have to ~~add autoedges to svc and~~ validate the time.
I didn't initially realize there was already a timer resource :P so I can rename this to something else, but is https://github.com/purpleidea/mgmt/blob/master/engine/resources/timer.go still useful given language functions?
Either way, I think it makes sense to call this resource 'timer' or 'systemd:timer' rather than cron.
Edit: also tests
=> [WIP] engine: resources: timer: Add a systemd-timer resource

util/util.go, util/util_test.go
This commit adds a []string{} type alias named PathSlice, and the
Len(), Swap(), and Less() methods required to satisfy sort.Interface.
Now you can do `sort.Sort(util.PathSlice(foo))` where foo is a slice
of paths. It will be sorted by depth in alphabetical order.
=> util: Add PathSlice type that satisfies sort.Interface

langpuppet/gapi.go
Since the langpuppet GAPI creates fresh new CliContext objects,
it has to make sure to provide the original parent context, because
the child GAPIs expect to be able to access its data.
=> langpuppet: Fix Cli method invocations for wrapped GAPIs

misc/make-deps.sh
Signed-off-by: Lander Van den Bulcke <landervdb@inuits.eu>
The flags `--no-ri` and `--no-rdoc` for `gem install` have been deprecated since version 2.0.0 and have actually been removed in 3.x.x. `--no-document` should be used instead.
=> make: Use gem --no-document instead of deprecated flags.

etcd/etcd.go, etcd/etcd_test.go, lib/cli.go, lib/main.go, lib/run.go, test/shell/clustersize.sh, test/shell/exchange.sh, test/shell/exchange0.mcl, test/shell/ipv6-localhost.sh, test/shell/no-network.sh, test/test-gotest.sh
I know some changes to the etcd code are upcoming. But these changes might be simple enough to already incorporate.
Changes:
* Allow unix domain socket to be used as client url
* Using ::1 as clienturl should not create default local ipv4 listener: http://[::1]:
* Adds `no-network-standalone` option which starts the server without any TCP ports open
The reason behind this is that open TCP ports make the mgmt daemon vulnerable as long as authentication is not implemented. Using `unix://` sockets allows authorization using file system permissions and allows to run a isolated mgmt daemon to run safely. By default the sockets for standalone are created in the prefix directory which should be secured anyway.
This feature was originally posted as: https://github.com/purpleidea/mgmt/pull/343
In …
=>  etcd: Connection options (socket file, ipv6)

misc/make-deps.sh
Add pkg-config to fix builds with augeas and libvirt on macOS.
=> build: Fix macOS build

gapi/gapi.go, langpuppet/gapi.go, lib/cli.go, lib/main.go, lib/run.go, puppet/gapi.go
I removed the "no-watch-config" flag, since it was only ever written and never read.
Having it around creates the expectation that by default mgmt will put a watch on the config.
The test suite still passes locally.
@purpleidea let me know what you think.
=> Removed obsolete no-watch-config flag

lang/funcs/core/os/family_func.go
@purpleidea This adds detection for the arch linux family.
What do you mean with "Detect OS changes"? Updates? Arch Linux is a rolling release, but I could detect different distributions of Arch Linux via `/etc/os-release`.
=> added detection for arch linux family

engine/resources/nspawn.go
The `nspawn` resource fails if the systemd version string contains a suffix like in
```
242.19-1
```
This PR will trim this suffix should it exist
=> engine: resources: nspawn: Trim possible systemd version suffix

engine/resources/resources_test.go
This adds FileOwnerExpect as a new Step which allows validating if the owner was set properly on a resource.
=> engine: resources: Add a test case for resource owner check

lang/fuzz/Makefile
I missed renaming this after moving the fuzz.go from the lang package
to its own fuzz package.
=> lang: Fix wrong go-fuzz bin name

lang/funcs/core/net/macfmt_func.go, lang/funcs/core/net/macfmt_func_test.go, lang/funcs/core/net/net.go
* Add new `net` package that implements `mcl` function related to networking.
* Add `mcl` function that takes a mac address with hyphens as an argument and converts it to a format with colons.
=> lang: funcs: Add macfmt function

misc/make-deps.sh
Fix the dependency path for dvyukov/go-fuzz to github.com from golang.org.
Fixes #601
```topic: Capitalized message with no trailing period```
or:
```topic, topic2: Capitalized message with no trailing period```
```
```
```
```
```
``` …
=> misc: Incorrect dependency path for dvyukov/go-fuzz

lang/inputs.go
Contradictory to expectations, `mgmt run lang metadata.yaml` would
produce an error similar to the following, which is likely unexpected
from the user perspective:
2020-11-24 12:24:08.330968 I | cli: lang: lexing/parsing...
2020-11-24 12:24:08.331153 I | run: error: cli parse error: could not generate AST: parser: `syntax error: unexpected DOT` @1:1
Produce a user-friendly warning instead, hinting with the supported
usage:
2020-11-24 13:15:01.686659 I | run: error: cli parse error: could not activate an input parser: unexpected raw code 'metadata.yaml'. Did you mean './metadata.yaml'?
=> Assert that 'metadata.yaml' is not parsed as raw mcl

test/test-markdownlint.sh
Fix the silent test failure by catching the uncaught error from
`command`, handling the failure gracefully.
$ bash -x test/test-markdownlint.sh
...
++ command -v mdl
+ MDL=
$ echo $?
1
$ bash -x test/test-markdownlint.sh
...
++ command -v mdl
+ MDL=
+ true
+ '[' -z '' ']'
+ fail_test 'The '\''mdl'\'' utility can'\''t be found.'
+ echo -e 'FAIL: The '\''mdl'\'' utility can'\''t be found.'
FAIL: The 'mdl' utility can't be found.
Fix a couple of glaring shellcheck warnings and errors mostly
surrounding variable quoting.
=> test: Fix implicit test fail in test-markdownlint

lang/types/value.go, lang/types/value_test.go
Replace use of reflect.Value.Len() with NumField() which is intended to
return the number of fields in reflected Struct value.
Len should only be used for Array, Chan, Map, Slice and String types.
Add some trivial sanity check tests for ValueOf() for the simple and
complex container types.
=> lang: Fix panic in lang/types/ValueOf() for Struct

engine/util/util.go, examples/lang/virt2.mcl, lang/structs.go, lang/types/type.go, lang/types/type_test.go, lang/types/util.go, lang/types/util_test.go, lang/types/value.go, lang/types/value_test.go
Into() mutates a given reflect.Value and sets the data represented by
the types.Value into the storage represented by the reflect.Value.
Into() is the opposite to ValueOf() which converts reflect.Value into
types.Value, and in theory they should (almost) bijective with some edge
case exceptions where the conversion is lossy.
Simply, it replaces reflect.Value.Set() in the broad case, giving finer
control of how the reflect.Value is modified and how the data is set.
types.Value.Value() is now also a redundant function that achieves the
same outcome as Into(), but with less type specificity.
---
lang: convert StmtRes to engine.Res with types.Into()
Replace existing field-mapping code with calls to types.Into() to
reflect the mcl data into the Go resource struct with finer granularity
and …
=> lang: Implement Value.Into() to reflect.Value representations

.gitmodules, engine/resources/docker_container.go, engine/resources/docker_container_test.go
These dependencies are maintained because the upstream repos bundle
vendor directories into the repos, which cause namespacing issues during
build. Git submodules don't strip the vendor directory whereas most
vendoring tools would.
This PR requires 
https://github.com/frebib/containerd/commit/231d09c8988e17f10853232bdee2441a4b4f3541
https://github.com/frebib/distribution/commit/a778dab7d0f94fcd7950a8eb439fa1accb445839
https://github.com/frebib/docker/commit/6c6f9d8cf0bae08f7c91c6794906eba3ebac9205
I think this is probably the only major downside to using git submodules over the equivalent vendoring tools that take language-specific problems into account, such as vendored dependencies inside vendored dependencies.
=> docker: Bump docker dependencies, add containerd

test/test-commit-message.sh
test-commit-message runs on PR, but also on push in other branches
which aren't PRs. We need to test those too.
This is fixed by ensuring the same kind of behaviour than travis CI:
When a patch is put on a branch, it's using the branchname for
testing [1].
[1]:
https://docs-staging.travis-ci.com/user/environment-variables/#default-environment-variables
=> test: Ensure branches are also testable

test/test-commit-message.sh
Without this patch, github actions fail.
It's a temporary workaround until [1] is done.
[1]: https://github.com/purpleidea/mgmt/issues/643
=> test: Add guard when no commit needs testing

engine/resources/docker_container.go, engine/resources/docker_image.go
docker/client.NewClient() is deprecated in favour of NewClientWithOpts()
which takes a series of client.Opt functions to configure the API
client. As mgmt only passes the API version through, this simplifies the
NewClient() calls.
=> engine: resources: docker: Replace deprecated NewClient() with NewClientWithOpts()

test/test-commit-message.sh
This should print more fields than just 3rd one if they're present.
=> test: Fix awk usage for printing refs

README.md, docs/faq.md
#mgmtconfig has moved to Libera.Chat as the primary channel for IRC
communications. Update the documentation to reflect this.
Libera.Chat doesn't provide a first-party web portal but does recommend
a few in the linked documentation on the website. As there is no
suitable replacement for webchat.freenode.net, link to the "Choosing an
IRC client" page instead.
=> docs: Update IRC links to Libera.Chat

README.md, docs/faq.md
Only a few days after updating the documentation[1] following the move
to libera.chat, the webchat client was added, mirroring the behaviour of
the documentation prior to the change. Replace the ircs:// links with
clickable URLs to a usable browser chat client, which is more ideal for
beginners. Advanced users will know what to do to connect using their
external client as normal
[1]: 7d7e225823fd2920c425c9c9518f739a5989b541
=> docs: Provide Libera.Chat webchat links over of irc://

lang/Makefile, lang/interpolate/parse.rl, lang/interpret_test/TestAstFunc2/escaping1.output, lang/interpret_test/TestAstFunc2/escaping1/main.mcl, lang/interpret_test/TestAstFunc2/escaping4.output, lang/interpret_test/TestAstFunc2/escaping5.output
Dollar symbols were failing to parse when not followed by a non-brace,
non-dollar, non-EOF token and causing expected tests to fail. This
simplifies the rules to allow the remaining tests to succeed.
Fix and reinstate the final few failing tests, and add another.
Allow any escape sequence to be matched so that invalid sequences
produce a meaningful error message instead of a generic "cannot parse":
ast: interpolate: interpolating: V: \?
unhandled escape sequence token: \?
Tidy the related Makefile rule for generating the ragel parser.
=> lang: interpolate: Fix string interpolation of dollar symbols

misc/fpm-pack.sh
According to [1] "/usr/lib/systemd/system/" is where systemd files from installed packages are stored in Arch Linux
According to FPM docs, the '--prefix' flag configures the "path to prefix files with when building the target package" [2].
With this change the contains more than a single binary, replacing the prefix flag with an absolute path constructed from the same shell variable should be safe and reduce the risk of the prefix flag interferring with other files added to the package.
Open question:
A] Does this change work for all distributions mgmt packages get build for?
B] Is the systemd unit file path for packages consistent across linux distros?
[1] https://wiki.archlinux.org/title/Systemd#Writing_unit_files
[2] https://fpm.readthedocs.io/en/latest/cli-reference.html
=> Add systemd service file to release packages

engine/util/util.go
Unexported fields should be ignored when mapping structs from Golang to
mcl, as this avoids issues where certain structs cannot be used in mcl
representation due to their structure that may be incompatible with
conversion. Disallowing private fields allows those to still be included
in the struct but ignored when mapping the types, allowing the mcl
representation of the type to stil be valid
Resolves: https://github.com/purpleidea/mgmt/issues/684
=> engine: util: Skip unexported fields in struct field mapping

docker/Dockerfile-fedora.build, docs/quick-start-guide.md, misc/make-deps.sh, test.sh, test/shell/etcd-three-hosts-reversed.sh, test/shell/etcd-three-hosts.sh, test/shell/etcd-two-hosts-reversed.sh, test/shell/etcd-two-hosts.sh, test/shell/exchange.sh, test/shell/exec-usergroup.sh, test/shell/ipv6-localhost.sh, test/shell/net.sh, test/shell/no-network.sh, test/shell/t2.sh, test/shell/t3.sh, test/shell/yaml-change1.sh, test/test-gotest.sh, test/test-yamlfmt.sh, test/util.sh
This PR provides a way to build mgmt for Fedora using a container.
When following the [quick start guide](https://github.com/purpleidea/mgmt/blob/master/docs/quick-start-guide.md) for the first time, none of the offered methods to build mgmt worked.
To ensure regel 6.1 is installed instead of the 7.0, I had to refactor test/util.sh and misc/make-deps.sh. This is why the `in_ci` method became `in_env`.
Maybe it would have been better to just rebuild the RPM for latest version of Fedora. But I prefer to use a container to keep my workstation clean. Another idea would be to use github action. 
In the meantime this provide a solution, today, for newcomers.
=> Build mgmt from a Fedora container

lang/ast/structs.go, lang/interpret_test/TestAstFunc2/clear-env-on-var.txtar
Variables are defined at the top-level, where only obj.Scope variables are in scope. The lambda parameters which are in scope where the variable is used must not be in scope where the variable is defined. This test detects future mistakes in which we make a recursive call with the same environment as the use site instead of clearing the env.
The test passes with or without the fix, because an earlier phase (SetScope) already clears the env, thus triggering a compile-time error.
=> lang: ast: Clear env in VarExpr.Graph

lang/ast/structs.go
From the Go specification [^1]:
> "1. ... For a nil slice, the number of iterations is 0."
Therefore, an additional nil check for around the loop is unnecessary.
[^1]: https://go.dev/ref/spec#For_range
/cc @purpleidea for review
=> lang: ast: Remove redundant nil check

docs/quick-start-guide.md
Fixes #752.
I did not investigate what's the problem with the Fedora Dockerfile or the buildah instructions but these instructions worked for me.
Also, I took the liberty to remove the note about outdated binaries since this made me try to build things myself in the first place. (But the binaries are not outdated at all.)
* please read the style guide before submitting your patch: (I didn't read it because this is only a documentation fix.)
=> Update docker build instructions

engine/resources/file.go
The owner/group of a file should not be validated on the host until runtime. This removes the checks in Validate() that were happening before the execution of the resource graph (and therefore bound to fail if the system was being bootstrapped).
Fixes #762
=> engine: resources: file: Remove Validate owner/group Checks

examples/lang/env0.mcl
Change the function call from `getenv` to `defaultenv`.
=> examples: lang: Fix env0 example

lang/core/net/url_parser.go, lang/interpret_test/TestAstFunc2/url_parser.txtar
This is a first attempt to adding a new function for URL parsing, using go's net/url package and the simple API. This is still a barebones implementation, there's possibility to expose more information that the stdlib exposes.
Related: https://github.com/purpleidea/mgmt/issues/606
=> lang: core: util: add a new func for URL parsing

modules/contrib/cryptpad/main.mcl
This is a module to deploy cryptpad locally - as it is, this is only intended for dev purposes, not for production environments
=> modules: misc: Add cryptpad module
